/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-01-02 08:02:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" +request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>登录&注册</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>Home</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"\" />\r\n");
      out.write("  \t<!-- Facebook and Twitter integration -->\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:image\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:url\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:site_name\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:description\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/owl.carousel.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <!-- MAIN CSS -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/tooplate-style.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/record.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,700\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/owl.carousel.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Animate.css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/animate.css\">\r\n");
      out.write("\t<!-- Icomoon Icon Fonts-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/icomoon.css\">\r\n");
      out.write("\t<!-- Themify Icons-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/themify-icons.css\">\r\n");
      out.write("\t<!-- Bootstrap  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Owl Carousel  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Theme style  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../plugins/layui/css/layui.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"../js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"gtco-loader\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"page-inner\">\r\n");
      out.write("\t<!-- MENU -->\r\n");
      out.write("\t<section class=\"navbar custom-navbar navbar-fixed-top top-nav-collapse\" role=\"navigation\" id=\"start\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t <div class=\"navbar-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  <!-- lOGO TEXT HERE -->\r\n");
      out.write("\t\t\t\t  <a href=\"../index.jsp\" class=\"navbar-brand\">VACARE</a>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t <!-- MENU LINKS -->\r\n");
      out.write("\t\t\t <div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t  <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../index.jsp\" class=\"smoothScroll\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../info/information.jsp\" class=\"smoothScroll\">疫苗资讯</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../info/query.jsp\" class=\"smoothScroll\">疫苗查询</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../maps/direction.jsp\" class=\"smoothScroll\">疫苗流向</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../maps/address.jsp\" class=\"smoothScroll\">接种信息</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../record/note.jsp\" class=\"smoothScroll\">疫苗本</a></li>\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t  <ul class=\"nav navbar-nav\" style=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t   <!-- 小人菜单栏-->\r\n");
      out.write("\t\t\t\t\t   <li class=\"dropdown\"><a href=\"login.jsp\" title=\"登录注册\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"fa fa-user-circle-o fa-lg\"></i></a>\r\n");
      out.write("\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t   <li class=\"dropdown\"><a data-toggle=\"dropdown\" title=\"修改信息\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"fa fa-cog fa-lg\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu settings-menu dropdown-menu-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=\"Info.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-edit fa-lg\"></i> &nbsp;个人资料</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=\"Password.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-cog fa-lg\"></i> &nbsp;修改密码</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=");
      out.print(request.getContextPath() +"/exit");
      out.write("><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-sign-out fa-lg\"></i>&nbsp; 安全退出</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("   </section>\r\n");
      out.write("\t\r\n");
      out.write("\t<header id=\"gtco-header\" class=\"gtco-cover\" role=\"banner\" style=\"background-image: url(images/home_bg.jpg)\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"gtco-container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 col-md-offset-0 text-left\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row row-mt-15em\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-7 mt-text animate-box\" data-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h1>Welcome to VACARE!</h1>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-md-push-1 animate-box\" data-animate-effect=\"fadeInRight\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"tab-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active gtco-first\"><a href=\"#\" data-tab=\"signup\">注册</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"gtco-second\"><a href=\"#\" data-tab=\"login\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-content-inner active\" data-content=\"signup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"username\">用户名</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"R_username\" name=\"R_username\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"password\">输入密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"R_password\" name=\"R_password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"password2\">重复密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"R_password2\" name=\"R_password2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" value=\"注册\" onclick=\"regist()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-content-inner\" data-content=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"username\">用户名</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"password\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-primary\" value=\"登录\" onclick=\"login()\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"gototop js-top\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- FOOTER -->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t <div class=\"row\">\r\n");
      out.write("\t\t\t\t  <div class=\"copyright-text col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t   <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Copyright &copy; 2020 VACARE - for all</p>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t   <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a data-scroll style=\"padding: 5px;\" href=\"../index.jsp\">返回首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("   </footer>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"../js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"../js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Carousel -->\r\n");
      out.write("\t<script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- countTo -->\r\n");
      out.write("\t<script src=\"../js/jquery.countTo.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"../js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"../js/magnific-popup-options.js\"></script>\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<script src=\"../js/main.js\"></script>\r\n");
      out.write("\t<script src=\"../plugins/layui/layui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\tvar username = $(\"#username\").val();\r\n");
      out.write("\tvar password = $(\"#password\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t if(username == \"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t   alert(\"请填写用户名！\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   else if(password == \"\")\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t \talert(\"请填写密码！\");\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t   else {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"../login\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("    \t\t   Name: username,\r\n");
      out.write("    \t\t   Password:password\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \tasync:false,\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tif(data != \"\"){\r\n");
      out.write("\t\t\t\talert(\"登录成功\");\r\n");
      out.write("\t\t\t\twindow.location.href=\"../index.jsp\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"登录失败\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("\t\t\talert(\"系统错误\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});  \r\n");
      out.write("   \t\t   \r\n");
      out.write("   \t   }\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function regist()\r\n");
      out.write("{\r\n");
      out.write("\tvar username = $(\"#R_username\").val();\r\n");
      out.write("\tvar password = $(\"#R_password\").val();\r\n");
      out.write("\tvar password2 = $(\"#R_password2\").val();\r\n");
      out.write("\r\n");
      out.write("\t if(username == \"\")\r\n");
      out.write("\t   {\r\n");
      out.write("\t   alert(\"请填写用户名！\");\r\n");
      out.write("\t   }\r\n");
      out.write(" else if(password == \"\" || password2 == \"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t \talert(\"请填写密码！\");\r\n");
      out.write("\t  }\r\n");
      out.write(" else if(password != password2)\r\n");
      out.write(" {\r\n");
      out.write("\t \talert(\"两次密码输入不相同！\");\r\n");
      out.write("\t  }\r\n");
      out.write(" else {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"../register\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tdata:{username:username,\r\n");
      out.write("\t\t\tpassword:password},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tif(data != \"\"){\r\n");
      out.write("\t\t\t\talert(\"注册成功!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert(\"用户名重复，注册失败!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("\t\t\talert(\"系统错误\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
