/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-12-24 07:57:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>CONVEST</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,700\">\r\n");
      out.write("    <!-- Bootstrap Select-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap-select/css/bootstrap-select.min.css\">\r\n");
      out.write("    <!-- owl carousel-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.theme.default.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("    <!-- Favicon and apple touch icons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"img/apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"img/apple-touch-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"img/apple-touch-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"img/apple-touch-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"img/apple-touch-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"img/apple-touch-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"img/apple-touch-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"img/apple-touch-icon-152x152.png\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("     <div id=\"all\">\r\n");
      out.write("      <!-- Top bar-->\r\n");
      out.write("      <div class=\"top-bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center\">\r\n");
      out.write("            <div class=\"col-md-6 d-md-block d-none\">\r\n");
      out.write("              <p>联系我们 +86 123456789 或者发送email至convest@gmail.com</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <div class=\"d-flex justify-content-md-end justify-content-between\">\r\n");
      out.write("                <ul class=\"list-inline contact-info d-block d-md-none\">\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-phone\"></i></a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-envelope\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"login\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\" class=\"login-btn\"><i class=\"fa fa-sign-in\"></i><span class=\"d-none d-md-inline-block\">登录</span></a><a href=\"customer-register.jsp\r\n");
      out.write("                \" class=\"signup-btn\"><i class=\"fa fa-user\"></i><span class=\"d-none d-md-inline-block\">注册</span></a></div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Top bar end-->\r\n");
      out.write("      <!-- Login Modal-->\r\n");
      out.write("      <div id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"login-modalLabel\" aria-hidden=\"true\" class=\"modal fade\">\r\n");
      out.write("        <div role=\"document\" class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 id=\"login-modalLabel\" class=\"modal-title\">用户登录</h4>\r\n");
      out.write("              <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">×</span></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <form action=\"个人中心.jsp\" method=\"get\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"email_modal\" type=\"text\" placeholder=\"email\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"password_modal\" type=\"password\" placeholder=\"密码\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <p cl/////ass=\"text-center\">\r\n");
      out.write("                  <button class=\"btn btn-template-outlined\"><i class=\"fa fa-sign-in\"></i> 登录</button>\r\n");
      out.write("                </p>\r\n");
      out.write("              </form>\r\n");
      out.write("              <p class=\"text-center text-muted\">还没注册？</p>\r\n");
      out.write("              <p class=\"text-center text-muted\"><a href=\"customer-register.jsp\"><strong>即刻注册</strong></a>! 只需一分钟，体验更多功能！</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Login modal end-->\r\n");
      out.write("      <!-- Navbar Start-->\r\n");
      out.write("      <header class=\"nav-holder make-sticky\">\r\n");
      out.write("        <div id=\"navbar\" role=\"navigation\" class=\"navbar navbar-expand-lg\">\r\n");
      out.write("          <div class=\"container\"><a href=\"首页.jsp\" class=\"navbar-brand home\"><img src=\"img/logo.png\" alt=\"Universal logo\" class=\"d-none d-md-inline-block\"><img src=\"img/logo-small.png\" alt=\"Universal logo\" class=\"d-inline-block d-md-none\"><span class=\"sr-only\">Universal - go to homepage</span></a>\r\n");
      out.write("            <button type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" class=\"navbar-toggler btn-template-outlined\"><span class=\"sr-only\">Toggle navigation</span><i class=\"fa fa-align-justify\"></i></button>\r\n");
      out.write("            <div id=\"navigation\" class=\"navbar-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"首页.jsp\" >首 页 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"高管信息.jsp\">高管信息 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"股票信息.jsp\" >股票信息<b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"社区资讯.jsp\" >社区资讯 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"个人中心.jsp\" >个人中心 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- ========== Contact dropdown end ==================-->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"collapse clearfix\">\r\n");
      out.write("              <form role=\"search\" class=\"navbar-form\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Search\" class=\"form-control\"><span class=\"input-group-btn\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-template-main\"><i class=\"fa fa-search\"></i></button></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <!-- Navbar End-->\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"heading-breadcrumbs\" class=\"brder-top-0 border-bottom-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center flex-wrap\">\r\n");
      out.write("            <div class=\"col-md-7\">\r\n");
      out.write("              <h1 class=\"h2\">联系我们</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-5\">\r\n");
      out.write("              <ul class=\"breadcrumb d-flex justify-content-end\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"首页.jsp\">主页</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\">联系我们</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <div id=\"contact\" class=\"container\">\r\n");
      out.write("          <section class=\"bar\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"heading\">\r\n");
      out.write("                  <h2>我们愿意与您成为合作伙伴</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"lead\">Are you curious about something? Do you have some kind of problem with our products? As am hastily invited settled at limited civilly fortune me. Really spring in extent an by. Judge but built gay party world. Of so am he remember although required. Bachelor unpacked be advanced at. Confined in declared marianne is vicinity.</p>\r\n");
      out.write("                <p class=\"text-sm\">Please feel free to contact us, our customer service center is working for you 24/7.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </section>\r\n");
      out.write("          <section>\r\n");
      out.write("            <div class=\"row text-center\">\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"box-simple\">\r\n");
      out.write("                  <div class=\"icon-outlined\"><i class=\"fa fa-map-marker\"></i></div>\r\n");
      out.write("                  <h3 class=\"h4\">地址</h3>\r\n");
      out.write("                  <p>中国上海杨浦区<br>                                        国定路777号上海财经大学<br>                                        信息管理与工程学院 <strong>520室</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"box-simple\">\r\n");
      out.write("                  <div class=\"icon-outlined\"><i class=\"fa fa-phone\"></i></div>\r\n");
      out.write("                  <h3 class=\"h4\">电话联系</h3>\r\n");
      out.write("                  <p>如果您在使用我们产品的过程中遇到问题或想提出建议，您可以免费联系我们。</p>\r\n");
      out.write("                  <p><strong>+86 123456789</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"box-simple\">\r\n");
      out.write("                  <div class=\"icon-outlined\"><i class=\"fa fa-envelope\"></i></div>\r\n");
      out.write("                  <h3 class=\"h4\">电子邮件</h3>\r\n");
      out.write("                  <p></p>\r\n");
      out.write("                  <ul class=\"list-unstyled text-sm\">\r\n");
      out.write("                    <p>您可以发送信息到我们的工作邮箱，我们会及时回复。</p>\r\n");
      out.write("                    <li><strong><a href=\"mailto:\">CONVEST@gmail.com</a></strong></li>\r\n");
      out.write("                   \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </section>\r\n");
      out.write("          <section class=\"bar pt-0\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"heading text-center\">\r\n");
      out.write("                  <h2>联系表</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-8 mx-auto\">\r\n");
      out.write("                <form>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"firstname\">姓</label>\r\n");
      out.write("                        <input id=\"firstname\" type=\"text\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"lastname\">名</label>\r\n");
      out.write("                        <input id=\"lastname\" type=\"text\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\">Email</label>\r\n");
      out.write("                        <input id=\"email\" type=\"text\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"subject\">公司</label>\r\n");
      out.write("                        <input id=\"subject\" type=\"text\" class=\"form-control\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-12\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"message\">留言</label>\r\n");
      out.write("                        <textarea id=\"message\" class=\"form-control\"></textarea>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-12 text-center\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-template-outlined\"><i class=\"fa fa-envelope-o\"></i> 发送表单</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </section>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--引用百度地图API-->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://api.map.baidu.com/api?key=&v=1.1&services=true\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!--百度地图容器-->\r\n");
      out.write("  <div class=\"row\" >\r\n");
      out.write("  <div style=\"width:1900px;height:250px;margin=auto\"  id=\"dituContent\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //创建和初始化地图函数：\r\n");
      out.write("    function initMap(){\r\n");
      out.write("        createMap();//创建地图\r\n");
      out.write("        setMapEvent();//设置地图事件\r\n");
      out.write("        addMapControl();//向地图添加控件\r\n");
      out.write("        addMarker();//向地图中添加marker\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //创建地图函数：\r\n");
      out.write("    function createMap(){\r\n");
      out.write("        var map = new BMap.Map(\"dituContent\");//在百度地图容器中创建一个地图\r\n");
      out.write("        var point = new BMap.Point(121.504758,31.308203);//定义一个中心点坐标\r\n");
      out.write("        map.centerAndZoom(point,18);//设定地图的中心点和坐标并将地图显示在地图容器中\r\n");
      out.write("        window.map = map;//将map变量存储在全局\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //地图事件设置函数：\r\n");
      out.write("    function setMapEvent(){\r\n");
      out.write("        map.enableDragging();//启用地图拖拽事件，默认启用(可不写)\r\n");
      out.write("        map.enableScrollWheelZoom();//启用地图滚轮放大缩小\r\n");
      out.write("        map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)\r\n");
      out.write("        map.enableKeyboard();//启用键盘上下左右键移动地图\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //地图控件添加函数：\r\n");
      out.write("    function addMapControl(){\r\n");
      out.write("        //向地图中添加缩放控件\r\n");
      out.write("\tvar ctrl_nav = new BMap.NavigationControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT,type:BMAP_NAVIGATION_CONTROL_SMALL});\r\n");
      out.write("\tmap.addControl(ctrl_nav);\r\n");
      out.write("                //向地图中添加比例尺控件\r\n");
      out.write("\tvar ctrl_sca = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});\r\n");
      out.write("\tmap.addControl(ctrl_sca);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //标注点数组\r\n");
      out.write("    var markerArr = [{title:\"CONVEST\",content:\"我们的地址\",point:\"121.504556|31.308504\",isOpen:0,icon:{w:21,h:21,l:0,t:0,x:6,lb:5}}\r\n");
      out.write("\t\t ];\r\n");
      out.write("    //创建marker\r\n");
      out.write("    function addMarker(){\r\n");
      out.write("        for(var i=0;i<markerArr.length;i++){\r\n");
      out.write("            var json = markerArr[i];\r\n");
      out.write("            var p0 = json.point.split(\"|\")[0];\r\n");
      out.write("            var p1 = json.point.split(\"|\")[1];\r\n");
      out.write("            var point = new BMap.Point(p0,p1);\r\n");
      out.write("\t\t\tvar iconImg = createIcon(json.icon);\r\n");
      out.write("            var marker = new BMap.Marker(point,{icon:iconImg});\r\n");
      out.write("\t\t\tvar iw = createInfoWindow(i);\r\n");
      out.write("\t\t\tvar label = new BMap.Label(json.title,{\"offset\":new BMap.Size(json.icon.lb-json.icon.x+10,-20)});\r\n");
      out.write("\t\t\tmarker.setLabel(label);\r\n");
      out.write("            map.addOverlay(marker);\r\n");
      out.write("            label.setStyle({\r\n");
      out.write("                        borderColor:\"#808080\",\r\n");
      out.write("                        color:\"#333\",\r\n");
      out.write("                        cursor:\"pointer\"\r\n");
      out.write("            });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t(function(){\r\n");
      out.write("\t\t\t\tvar index = i;\r\n");
      out.write("\t\t\t\tvar _iw = createInfoWindow(i);\r\n");
      out.write("\t\t\t\tvar _marker = marker;\r\n");
      out.write("\t\t\t\t_marker.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\t\t    this.openInfoWindow(_iw);\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t    _iw.addEventListener(\"open\",function(){\r\n");
      out.write("\t\t\t\t    _marker.getLabel().hide();\r\n");
      out.write("\t\t\t    })\r\n");
      out.write("\t\t\t    _iw.addEventListener(\"close\",function(){\r\n");
      out.write("\t\t\t\t    _marker.getLabel().show();\r\n");
      out.write("\t\t\t    })\r\n");
      out.write("\t\t\t\tlabel.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\t\t    _marker.openInfoWindow(_iw);\r\n");
      out.write("\t\t\t    })\r\n");
      out.write("\t\t\t\tif(!!json.isOpen){\r\n");
      out.write("\t\t\t\t\tlabel.hide();\r\n");
      out.write("\t\t\t\t\t_marker.openInfoWindow(_iw);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})()\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    //创建InfoWindow\r\n");
      out.write("    function createInfoWindow(i){\r\n");
      out.write("        var json = markerArr[i];\r\n");
      out.write("        var iw = new BMap.InfoWindow(\"<b class='iw_poi_title' title='\" + json.title + \"'>\" + json.title + \"</b><div class='iw_poi_content'>\"+json.content+\"</div>\");\r\n");
      out.write("        return iw;\r\n");
      out.write("    }\r\n");
      out.write("    //创建一个Icon\r\n");
      out.write("    function createIcon(json){\r\n");
      out.write("        var icon = new BMap.Icon(\"http://app.baidu.com/map/images/us_mk_icon.png\", new BMap.Size(json.w,json.h),{imageOffset: new BMap.Size(-json.l,-json.t),infoWindowOffset:new BMap.Size(json.lb+5,1),offset:new BMap.Size(json.x,json.h)})\r\n");
      out.write("        return icon;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    initMap();//创建和初始化地图\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("      <!-- FOOTER -->\r\n");
      out.write("     <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">联系方式</h4>\r\n");
      out.write("              <p>企业邮箱：<a href=\"mailto:CONVEST@gmail.com\" rel=\"nofollow\">CONVEST@gmail.com</a></p>\r\n");
      out.write("              <p>联系电话：+86 1234567</p>\r\n");
      out.write("              <p>工作时间：周一至周五：9:30-17:00</p>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <h4 class=\"h6\">真诚欢迎合作者的到来！</h4>\r\n");
      out.write("              \r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">数据来源</h4>\r\n");
      out.write("              <p><a href=\"http://zxgk.court.gov.cn/\" target=\"_blank\" rel=\"nofollow\">中国执行信息公开网</a></p>\r\n");
      out.write("              <p><a href=\"http://www.sipo.gov.cn/\" target=\"_blank\" rel=\"nofollow\">国家知识产权局</a></p>\r\n");
      out.write("              <p><a href=\"http://sbj.cnipa.gov.cn/\" target=\"_blank\" rel=\"nofollow\">商标局</a></p>\r\n");
      out.write("              <p><a href=\"http://www.ncac.gov.cn/\" target=\"_blank\" rel=\"nofollow\">版权局</a></p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">办公地址</h4>\r\n");
      out.write("              <p class=\"text-uppercase\"><strong>中国上海杨浦区</strong><br>国定路777号 <br>上海财经大学<br>信息管理与工程学院<br><strong></strong></p><a href=\"contact.jsp\" class=\"btn btn-template-main\">前往联系界面</a>\r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyrights\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-lg-4 text-center-md\">\r\n");
      out.write("                <p>&copy; 2020. CONVEST</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Javascript files-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/waypoints/lib/jquery.waypoints.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/jquery.counterup/jquery.counterup.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.parallax-1.1.3.js\"></script>\r\n");
      out.write("    <script src=\"vendor/bootstrap-select/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.scrollto/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ\"></script>\r\n");
      out.write("    <script src=\"js/gmaps.js\"></script>\r\n");
      out.write("    <script src=\"js/gmaps.init.js\"></script>\r\n");
      out.write("    <script src=\"js/front.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
