/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-01-05 19:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 社区资讯_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>CONVEST</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,700\">\r\n");
      out.write("    <!-- Bootstrap Select-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap-select/css/bootstrap-select.min.css\">\r\n");
      out.write("    <!-- owl carousel-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.theme.default.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("    <!-- Favicon and apple touch icons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"img/apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"img/apple-touch-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"img/apple-touch-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"img/apple-touch-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"img/apple-touch-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"img/apple-touch-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"img/apple-touch-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"img/apple-touch-icon-152x152.png\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"all\">\r\n");
      out.write("      <!-- Top bar-->\r\n");
      out.write("      <div class=\"top-bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center\">\r\n");
      out.write("            <div class=\"col-md-6 d-md-block d-none\">\r\n");
      out.write("              <p>联系我们 +86 123456789 或者发送email至convest@gmail.com</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <div class=\"d-flex justify-content-md-end justify-content-between\">\r\n");
      out.write("                <ul class=\"list-inline contact-info d-block d-md-none\">\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-phone\"></i></a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-envelope\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"login\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\" class=\"login-btn\"><i class=\"fa fa-sign-in\"></i><span class=\"d-none d-md-inline-block\">登录</span></a><a href=\"customer-register.jsp\" class=\"signup-btn\"><i class=\"fa fa-user\"></i><span class=\"d-none d-md-inline-block\">注册</span></a></div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Top bar end-->\r\n");
      out.write("      <!-- Login Modal-->\r\n");
      out.write("      <div id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledFrom=\"login-modalLabel\" aria-hidden=\"true\" class=\"modal fade\">\r\n");
      out.write("        <div role=\"document\" class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 id=\"login-modalLabel\" class=\"modal-title\">用户登录</h4>\r\n");
      out.write("              <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">×</span></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <form action=\"个人中心.jsp\" method=\"get\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"email_modal\" type=\"text\" placeholder=\"email\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"password_modal\" type=\"password\" placeholder=\"密码\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"text-center\">\r\n");
      out.write("                  <button class=\"btn btn-template-outlined\"><i class=\"fa fa-sign-in\"></i> 登录</button>\r\n");
      out.write("                </p>\r\n");
      out.write("              </form>\r\n");
      out.write("              <p class=\"text-center text-muted\">还没注册？</p>\r\n");
      out.write("              <p class=\"text-center text-muted\"><a href=\"customer-register.jsp\"><strong>即刻注册</strong></a>! 只需一分钟，体验更多功能！</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Login modal end-->\r\n");
      out.write("      <!-- Navbar Start-->\r\n");
      out.write("      <header class=\"nav-holder make-sticky\">\r\n");
      out.write("        <div id=\"navbar\" role=\"navigation\" class=\"navbar navbar-expand-lg\">\r\n");
      out.write("          <div class=\"container\"><a href=\"首页.jsp\" class=\"navbar-brand home\"><img src=\"img/logo.png\" alt=\"Universal logo\" class=\"d-none d-md-inline-block\"><img src=\"img/logo-small.png\" alt=\"Universal logo\" class=\"d-inline-block d-md-none\"><span class=\"sr-only\">CONVEST - go to homepage</span></a>\r\n");
      out.write("            <button type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" class=\"navbar-toggler btn-template-outlined\"><span class=\"sr-only\">Toggle navigation</span><i class=\"fa fa-align-justify\"></i></button>\r\n");
      out.write("            <div id=\"navigation\" class=\"navbar-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"首页.jsp\" >首 页 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"高管信息.jsp\">高管信息 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"股票信息.jsp\" >股票信息<b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown active\"><a href=\"社区资讯.jsp\" >社区资讯 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"个人中心.jsp\" >个人中心 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- ========== Contact dropdown end ==================-->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"collapse clearfix\">\r\n");
      out.write("              <form role=\"search\" class=\"navbar-form\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Search\" class=\"form-control\"><span class=\"input-group-btn\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-template-main\"><i class=\"fa fa-search\"></i></button></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <!-- Navbar End-->\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"heading-breadcrumbs\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center flex-wrap\">\r\n");
      out.write("            <div class=\"col-md-7\">\r\n");
      out.write("              <h1 class=\"h2\">看一看：财圈新鲜事</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-5\">\r\n");
      out.write("              <ul class=\"breadcrumb d-flex justify-content-end\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"首页.jsp\">首页</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\">社区资讯</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <section class=\"bar no-padding-bottom\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </section>\r\n");
      out.write("            \r\n");
      out.write("              \r\n");
      out.write("      <!-- LEFT COLUMN _________________________________________________________-->\r\n");
      out.write("              <div id=\"blog-listing-big\" class=\"col-md-9\">\r\n");
      out.write("                  <div class=\"post\" id=\"qeone\">\r\n");
      out.write("                      <h2><a>推荐资讯</a></h2>\r\n");
      out.write("                    \r\n");
      out.write("                          \r\n");
      out.write("                         <br>\r\n");
      out.write("                   <div class=\"post\" id=\"qeone\">\r\n");
      out.write("                      <h3><a id=\"title1\">我国国防法修订 明年1月1日起施行</a></h3>\r\n");
      out.write("                       <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name1\">新华社 刘硕</a></p>\r\n");
      out.write("                              <p>据介绍，此次主要修改内容包括：确立了习近平新时代中国特色社会主义思想在国防活动中的指导地位；结合党和国家机构改革、国防和军队改革实际，调整了国家机构的国防职权，增加了军委主席负责制的内容；充实了武装力量的任务和建设目标；着眼新型安全领域活动和利益的防卫需要，明确了重大安全领域防卫政策；根据国防教育和国防动员领导管理体制改革实际，充实完善了国防教育和国防动员制度；着眼“使军人成为全社会尊崇的职业”，强化了对军人地位和权益的保护；贯彻总体国家安全观和习近平外交思想，充实了对外军事关系方面的政策制度。\r\n");
      out.write("                          </div>\r\n");
      out.write("                          \r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"post\" id=\"qetwo\">\r\n");
      out.write("                      <h3><a id=\"title2\">2021年商务工作要干这些事</a></h3>\r\n");
      out.write("                      <div class=\"row\" >\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name2\">新华社 于佳欣 王雨萧</a></p>\r\n");
      out.write("                              <p>这是商务部于26日召开的全国商务工作电视电话会议释放的信息。会议指出，尽管面对严峻复杂的国际形势特别是新冠肺炎疫情严重冲击，我国稳住外贸外资基本盘，推动消费回升，实现了商务发展回稳向好、好于预期。 </p>\r\n");
      out.write("                          </div>                 \r\n");
      out.write("                      </div> \r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"post\" id=\"qethree\">\r\n");
      out.write("                      <h3><a id=\"title3\">广西两个铁路项目26日开工建设</a></h3>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name3\">新华社 林凡诗</a></p>\r\n");
      out.write("                              <p>新建柳州至广州铁路柳州至梧州段为我国中长期铁路网规划中柳州至广州铁路的组成部分，项目正线全长237.8公里，沿线经柳州、来宾、贵港、梧州4市，为国铁I级、双线电气化、客货共线铁路，设计时速160公里，批复建设工期4年。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"post\" id=\"qefour\">\r\n");
      out.write("                      <h3><a id=\"title4\">“新媒体影响力指数”TOP10、“微信原创传播力指数”TOP10榜单揭晓</a></h3>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name4\">传媒茶话会微信公众号</a></p>\r\n");
      out.write("                            \r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                   <div class=\"post\" id=\"qefive\">\r\n");
      out.write("                      <h3><a id=\"title5\">特写：面对审计整改追问，部长们这样回答</a></h3>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name5\">新华社 刘红霞</a></p>\r\n");
      out.write("                              <p>“请问国家发展改革委，部分项目未按时开工的原因是什么？针对地方实施的项目存在开工慢，或者未开工的情况是如何跟踪督促整改的？请问财政部，部分项目资金拨付进度滞后的原因是什么？在加快项目资金拨付进度方面，将采取哪些措施？两个部门在加强部门间协调沟通方面，有哪些举措？”面对国务院相关部门主要负责同志，全国人大常委会委员吕薇连发五问。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"post\" id=\"qesix\">\r\n");
      out.write("                      <h3><a id=\"title6\">通过！我国出台长江保护法守护母亲河</a></h3>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name6\">新华社 高敬</a></p>\r\n");
      out.write("                              <p>长江保护法包括总则、规划与管控、资源保护、水污染防治、生态环境修复、绿色发展、保障与监督、法律责任和附则9章，共96条。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"post\" id=\"qeseven\">\r\n");
      out.write("                      <h3><a id=\"title7\">北京：加紧精准流调溯源和应检尽检</a></h3>\r\n");
      out.write("                      <div class=\"row\" >\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name7\">新华社 赵旭 孙蕾 田晨旭</a></p>\r\n");
      out.write("                              <p>北京市疾病预防控制中心副主任庞星火在发布会上介绍，根据疫情防控工作需要，北京市对朝阳区3个街道、顺义区12个街道乡镇和天竺综保区相关人员进行核酸检测，实行应检尽检。经过初步检测，有5人核酸检测为阳性，均为25日北京确诊病例的密切接触者，市、区疾控机构、医疗机构正在进行复核与诊断，结果待报，不排除进一步发现病例的可能。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>                \r\n");
      out.write("                  <div class=\"post\" id=\"qeeight\" style=\"display:none\">\r\n");
      out.write("                      <h3><a id=\"title8\">武汉城市圈第5条城际铁路正式开通运营</a></h3>\r\n");
      out.write("                      <div class=\"row\" >\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name8\">新华社 王贤</a></p>\r\n");
      out.write("                              <p>新建仙桃城际线全长近17公里，标准等级为双线城际铁路，设计行车时速200公里，自汉川站至天门南站间的大福村接轨引入汉宜铁路。这条铁路线新建大福、仙桃两个车站，其中仙桃站为尽头式客运站，大福站为列车会让站不办理客运业务。武（汉）仙（桃）城际铁路线由新建仙桃城际线和既有汉宜铁路线组成，全程87公里，最快历时41分钟。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"post\" id=\"qenine\" style=\"display:none\">\r\n");
      out.write("                      <h3><a id=\"title12\">全国商务工作电视电话会议召开 部署2021年重点工作</a></h3>\r\n");
      out.write("                      <div class=\"row\" >\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name9\">上海证券报·中国证券网</a></p>\r\n");
      out.write("                              <p>会议指出，今年以来，面对严峻复杂的国际形势特别是新冠肺炎疫情严重冲击，在以习近平同志为核心的党中央坚强领导下，全国商务系统认真落实党中央、国务院决策部署，统筹疫情防控和商务发展，团结奋进、迎难而上，稳住了外贸外资基本盘，推动了消费回升，实现了商务发展回稳向好、好于预期。消费稳步复苏，新业态新模式蓬勃发展。外贸再创新高，结构进一步优化。利用外资逆势增长，大项目稳步推进。对外投资有序发展。多双边经贸合作取得新突破。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                 \r\n");
      out.write("                   <div class=\"post\" id=\"qeten\" style=\"display:none\">\r\n");
      out.write("                      <h3><a id=\"title10\">三个月时间，广州浪奇“黑洞”扩大了50%，何时是尽头？</a></h3>\r\n");
      out.write("                       <div class=\"row\" >\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                              <p class=\"author-category\">From <a id=\"name10\">上海证券报微信公众号 邱德坤</a></p>\r\n");
      out.write("                              <p>不断扩大的“黑洞”，正在吞噬广州浪奇60年时光积淀的声誉和财富，也给广州浪奇的命运蒙上了不可预知的阴影。</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>       \r\n");
      out.write("             \r\n");
      out.write("              \r\n");
      out.write("      <!-- FOOTER -->\r\n");
      out.write("     <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">联系方式</h4>\r\n");
      out.write("              <p>企业邮箱：<a href=\"mailto:CONVEST@gmail.com\" rel=\"nofollow\">CONVEST@gmail.com</a></p>\r\n");
      out.write("              <p>联系电话：+86 1234567</p>\r\n");
      out.write("              <p>工作时间：周一至周五：9:30-17:00</p>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <h4 class=\"h6\">真诚欢迎合作者的到来！</h4>\r\n");
      out.write("              \r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">数据来源</h4>\r\n");
      out.write("              <p><a href=\"http://zxgk.court.gov.cn/\" target=\"_blank\" rel=\"nofollow\">中国执行信息公开网</a></p>\r\n");
      out.write("              <p><a href=\"http://www.sipo.gov.cn/\" target=\"_blank\" rel=\"nofollow\">国家知识产权局</a></p>\r\n");
      out.write("              <p><a href=\"http://sbj.cnipa.gov.cn/\" target=\"_blank\" rel=\"nofollow\">商标局</a></p>\r\n");
      out.write("              <p><a href=\"http://www.ncac.gov.cn/\" target=\"_blank\" rel=\"nofollow\">版权局</a></p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">办公地址</h4>\r\n");
      out.write("              <p class=\"text-uppercase\"><strong>中国上海杨浦区</strong><br>国定路777号 <br>上海财经大学<br>信息管理与工程学院<br><strong></strong></p><a href=\"contact.jsp\" class=\"btn btn-template-main\">前往联系界面</a>\r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyrights\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-lg-4 text-center-md\">\r\n");
      out.write("                <p>&copy; 2020. CONVEST</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Javascript files-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/waypoints/lib/jquery.waypoints.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/jquery.counterup/jquery.counterup.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.parallax-1.1.3.js\"></script>\r\n");
      out.write("    <script src=\"vendor/bootstrap-select/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.scrollto/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("    <script src=\"js/front.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"js/template.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("     function login(){\r\n");
      out.write(" \t\tvar myusername = $(\"#myusername\").val();\r\n");
      out.write(" \t\tvar mypassword = $(\"#mypassword\").val();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t if(myusername == \"\")\r\n");
      out.write(" \t\t\t   {\r\n");
      out.write(" \t\t\t   alert(\"请填写用户名！\");\r\n");
      out.write(" \t\t\t   }\r\n");
      out.write(" \t\t   else if(mypassword == \"\")\r\n");
      out.write(" \t\t\t  {\r\n");
      out.write(" \t\t\t \talert(\"请填写密码！\");\r\n");
      out.write(" \t\t\t  }\r\n");
      out.write(" \t\t   else {\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write(" \t\t\turl:\"login\",   \r\n");
      out.write(" \t\t\ttype:\"post\",\r\n");
      out.write(" \t\t\tdata:{\r\n");
      out.write(" \t    \t\t   Name: myusername,\r\n");
      out.write(" \t    \t\t   Password:mypassword,\r\n");
      out.write(" \t    \t\t},\r\n");
      out.write(" \t    \tasync:false,\r\n");
      out.write(" \t\t\tsuccess:function(data){\r\n");
      out.write(" \t\t\t\tif(data != \"\"){\r\n");
      out.write(" \t\t\t\t\talert(\"登录成功\");\r\n");
      out.write(" \t\t\t\t\twindow.location.href=\"首页.jsp\";\r\n");
      out.write(" \t\t\t\t}else{\r\n");
      out.write(" \t\t\t\t\talert(\"登录失败\");\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t},\r\n");
      out.write(" \t\t\terror:function(XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write(" \t\t\t\talert(\"系统错误\");\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t});  \r\n");
      out.write(" \t   \t\t   \r\n");
      out.write(" \t   \t   }\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t}\r\n");
      out.write("     </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
