/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-01-05 19:41:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class 股票信息_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>CONVEST</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,700\">\r\n");
      out.write("    <!-- Bootstrap Select-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap-select/css/bootstrap-select.min.css\">\r\n");
      out.write("    <!-- owl carousel-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.theme.default.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Favicon and apple touch icons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"img/apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"img/apple-touch-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"img/apple-touch-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"img/apple-touch-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"img/apple-touch-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"img/apple-touch-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"img/apple-touch-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"img/apple-touch-icon-152x152.png\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write(" <body>\r\n");
      out.write("    <div id=\"all\">\r\n");
      out.write("      <!-- Top bar-->\r\n");
      out.write("      <div class=\"top-bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center\">\r\n");
      out.write("            <div class=\"col-md-6 d-md-block d-none\">\r\n");
      out.write("              <p>联系我们 +86 123456789 或者发送email至convest@gmail.com</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <div class=\"d-flex justify-content-md-end justify-content-between\">\r\n");
      out.write("                <ul class=\"list-inline contact-info d-block d-md-none\">\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-phone\"></i></a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-envelope\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"login\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\" class=\"login-btn\"><i class=\"fa fa-sign-in\"></i><span class=\"d-none d-md-inline-block\">登录</span></a><a href=\"customer-register.jsp\" class=\"signup-btn\"><i class=\"fa fa-user\"></i><span class=\"d-none d-md-inline-block\">注册</span></a></div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Top bar end-->\r\n");
      out.write("      <!-- Login Modal-->\r\n");
      out.write("      <div id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"login-modalLabel\" aria-hidden=\"true\" class=\"modal fade\">\r\n");
      out.write("        <div role=\"document\" class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 id=\"login-modalLabel\" class=\"modal-title\">用户登录</h4>\r\n");
      out.write("              <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">×</span></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <form action=\"个人中心.jsp\" method=\"get\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"myusername\" type=\"text\" placeholder=\"用户名\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"mypassword\" type=\"password\" placeholder=\"密码\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"text-center\">\r\n");
      out.write("                  <button class=\"btn btn-template-outlined\" onclick=\"login()\"><i class=\"fa fa-sign-in\"></i> 登录</button>\r\n");
      out.write("                </p>\r\n");
      out.write("              </form>\r\n");
      out.write("              <p class=\"text-center text-muted\">还没注册？</p>\r\n");
      out.write("              <p class=\"text-center text-muted\"><a href=\"customer-register.jsp\"><strong>即刻注册</strong></a>! 只需一分钟，体验更多功能！</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Login modal end-->\r\n");
      out.write("      <!-- Navbar Start-->\r\n");
      out.write("      <header class=\"nav-holder make-sticky\">\r\n");
      out.write("        <div id=\"navbar\" role=\"navigation\" class=\"navbar navbar-expand-lg\">\r\n");
      out.write("          <div class=\"container\"><a href=\"首页.jsp\" class=\"navbar-brand home\"><img src=\"img/logo.png\" alt=\"Universal logo\" class=\"d-none d-md-inline-block\"><img src=\"img/logo-small.png\" alt=\"Universal logo\" class=\"d-inline-block d-md-none\"><span class=\"sr-only\">CONVSET - go to homepage</span></a>\r\n");
      out.write("            <button type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" class=\"navbar-toggler btn-template-outlined\"><span class=\"sr-only\">Toggle navigation</span><i class=\"fa fa-align-justify\"></i></button>\r\n");
      out.write("            <div id=\"navigation\" class=\"navbar-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"首页.jsp\" >首 页 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"高管信息.jsp\">高管信息 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown active\"><a href=\"股票信息.jsp\" >股票信息<b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"社区资讯.jsp\" >社区资讯 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"个人中心.jsp\" >个人中心 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>                <!-- ========== Contact dropdown end ==================-->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"collapse clearfix\">\r\n");
      out.write("              <form role=\"search\" class=\"navbar-form\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Search\" class=\"form-control\"><span class=\"input-group-btn\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-template-main\" ><i class=\"fa fa-search\"></i></button></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <!-- Navbar End-->\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"heading-breadcrumbs\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center flex-wrap\">\r\n");
      out.write("            <div class=\"col-md-7\">\r\n");
      out.write("              <h1 class=\"h2\">搜一搜：股票行情怎么样</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-5\">\r\n");
      out.write("              <ul class=\"breadcrumb d-flex justify-content-end\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"首页.jsp\">首页</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\">股票信息</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("       <div class=\"col-md-6\" >\r\n");
      out.write("      \r\n");
      out.write("                  <form role=\"search\" >\r\n");
      out.write("                    <div class=\"input-group\" >\r\n");
      out.write("                      <input type=\"text\" placeholder=\"输入股票代码或企业名称\" class=\"form-control\" id=\"stock_id\"><span class=\"input-group-btn\" id=\"template\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-template-main\"><i class=\"fa fa-search\"></i></button></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("             \r\n");
      out.write("      <section class=\"bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <!-- MENUS AND WIDGETS -->\r\n");
      out.write("              <div class=\"panel panel-default sidebar-menu with-icons\">\r\n");
      out.write("                <div class=\"panel-heading\">\r\n");
      out.write("                  <h3 class=\"h4 panel-title\">股票信息</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"panel-body\">\r\n");
      out.write("                  <ul class=\"nav nav-pills flex-column text-sm\">\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"股票信息.jsp\" class=\"nav-link active\">基本信息</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"template-alerts.jsp\" class=\"nav-link\">股票行情</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"template-content-boxes.jsp\" class=\"nav-link\">股东持股变动</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"template-blocks.jsp\" class=\"nav-link\">重大事项</a></li>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("              <div id=\"accordion\" role=\"tablist\" class=\"mb-5\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div id=\"headingOne\" role=\"tab\" class=\"card-header\">\r\n");
      out.write("                    <h5 class=\"mb-0\"><a data-toggle=\"collapse\" href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">查询结果如下</a></h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"collapseOne\" role=\"tabpanel\" aria-labelledby=\"headingOne\" data-parent=\"#accordion\" class=\"collapse show\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"stock_basic_info\">\r\n");
      out.write("      \r\n");
      out.write("         <table class=\"table table-hover table-bordered\" id=\"stock_info\">\r\n");
      out.write("                     <thead>\r\n");
      out.write("                                     <tr>\r\n");
      out.write("                                       <th style=\"width:100px\">所属地域</th>\r\n");
      out.write("                                       <th>所属行业</th>\r\n");
      out.write("                                       <th>董事长</th>\r\n");
      out.write("                                       <th>法人代表</th>\r\n");
      out.write("                                       <th>总经理</th>\r\n");
      out.write("                                       <th>总股本</th>\r\n");
      out.write("                                       <th>流通股本</th>\r\n");
      out.write("                                       <th>实际控制人</th>\r\n");
      out.write("                                       <th>产品类型</th>\r\n");
      out.write("                                       <th>公司信息</th>\r\n");
      out.write("                                     </tr>\r\n");
      out.write("                                   </thead>              \r\n");
      out.write("\r\n");
      out.write("\t  <tbody id=\"stock_info-body\">\t\t\r\n");
      out.write("\t </tbody>\r\n");
      out.write("\t <script type=\"text/html\" id=\"stock_info-script\">\r\n");
      out.write("{{each data value i}}\r\n");
      out.write("<tr class=\"table-data-line\">\r\n");
      out.write("<td> {{value.location}}</td>\r\n");
      out.write("<td> {{value.Industry}}</td>\r\n");
      out.write("<td> {{value.Chairman}}</td>\r\n");
      out.write("<td> {{value.LegalRepresentative}}</td>\r\n");
      out.write("<td> {{value.Manager}}</td>\r\n");
      out.write("<td> {{value.ShareholdingEquity}}</td>\r\n");
      out.write("<td> {{value.FlowEquity}}</td>\r\n");
      out.write("<td> {{value.Controller}}</td>\r\n");
      out.write("<td> {{value.ProductType}}</td>\r\n");
      out.write("<td> {{value.CompanyInfo}}</td>\r\n");
      out.write("</tr>\r\n");
      out.write("{{/each}}\t \r\n");
      out.write("\t </script>\r\n");
      out.write("\t </table>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("             \r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("             \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("     \r\n");
      out.write("      <!-- FOOTER -->\r\n");
      out.write("     <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">联系方式</h4>\r\n");
      out.write("              <p>企业邮箱：<a href=\"mailto:CONVEST@gmail.com\" rel=\"nofollow\">CONVEST@gmail.com</a></p>\r\n");
      out.write("              <p>联系电话：+86 1234567</p>\r\n");
      out.write("              <p>工作时间：周一至周五：9:30-17:00</p>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <h4 class=\"h6\">真诚欢迎合作者的到来！</h4>\r\n");
      out.write("              \r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">数据来源</h4>\r\n");
      out.write("              <p><a href=\"http://zxgk.court.gov.cn/\" target=\"_blank\" rel=\"nofollow\">中国执行信息公开网</a></p>\r\n");
      out.write("              <p><a href=\"http://www.sipo.gov.cn/\" target=\"_blank\" rel=\"nofollow\">国家知识产权局</a></p>\r\n");
      out.write("              <p><a href=\"http://sbj.cnipa.gov.cn/\" target=\"_blank\" rel=\"nofollow\">商标局</a></p>\r\n");
      out.write("              <p><a href=\"http://www.ncac.gov.cn/\" target=\"_blank\" rel=\"nofollow\">版权局</a></p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">办公地址</h4>\r\n");
      out.write("              <p class=\"text-uppercase\"><strong>中国上海杨浦区</strong><br>国定路777号 <br>上海财经大学<br>信息管理与工程学院<br><strong></strong></p><a href=\"contact.jsp\" class=\"btn btn-template-main\">前往联系界面</a>\r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyrights\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-lg-4 text-center-md\">\r\n");
      out.write("                <p>&copy; 2020. CONVEST</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <!-- Javascript files-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/waypoints/lib/jquery.waypoints.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/jquery.counterup/jquery.counterup.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.parallax-1.1.3.js\"></script>\r\n");
      out.write("    <script src=\"vendor/bootstrap-select/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.scrollto/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("    <script src=\"js/front.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"js/template.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write(" $('body').on('click', '#template', function () { \r\n");
      out.write("\t    \r\n");
      out.write("\t   \r\n");
      out.write("\t //   addrShow.value =provice[current.prov].name + '-' + provice[current.prov][\"city\"][current.city].name + '-' + provice[current.prov][\"city\"][current.city].districtAndCounty[current.country];\r\n");
      out.write("\t    jQuery.noConflict();\r\n");
      out.write("\t    jQuery('#stock_info').dataTable().fnDestroy();\r\n");
      out.write("\t    jQuery.ajax({\r\n");
      out.write("\t  \r\n");
      out.write("\t        url: \"Querystock_info\",\r\n");
      out.write("\t        type: \"post\",\r\n");
      out.write("\t        cache:false,\r\n");
      out.write("\t        data:{\r\n");
      out.write("\t        \tstock_id:jQuery(\"#stock_id\").val(),\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        },\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t        success: function (data) {\r\n");
      out.write("\t            console.log(data);\r\n");
      out.write("\t            jQuery(\"#stock_info-body\").empty();\r\n");
      out.write("\t            jQuery(\"#stock_info-body\").append(template(\"stock_info-script\", { data: data }));\r\n");
      out.write("\t            \r\n");
      out.write("\t        }, error: function (data) {\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t   \r\n");
      out.write(" });\r\n");
      out.write("\tjQuery('#stock_info').dataTable({\r\n");
      out.write("\t     \"bLengthChange\": false, //开关，是否显示每页显示多少条数据的下拉框\r\n");
      out.write("\t     'iDisplayLength': 2, //每页初始显示5条记录\r\n");
      out.write("\t     'bFilter': false,  //是否使用内置的过滤功能（是否去掉搜索框）\r\n");
      out.write("\t     \"bInfo\": false, //开关，是否显示表格的一些信息(当前显示XX-XX条数据，共XX条)\r\n");
      out.write("\t     \"bPaginate\": false, //开关，是否显示分页器\r\n");
      out.write("\t     \"bSort\": false, //是否可排序 \r\n");
      out.write("\r\n");
      out.write("\t     \"oLanguage\": {  //语言转换\r\n");
      out.write("\t       \"sInfo\": \"显示第 _START_ 至 _END_ 项结果，共_TOTAL_ 项\",\r\n");
      out.write("\t       \"sZeroRecords\": \"暂无数据呜呜呜\",\r\n");
      out.write("\t       \"sLengthMenu\": \"每页显示 _MENU_ 项结果\",\r\n");
      out.write("\t       \"oPaginate\": {\r\n");
      out.write("\t         \"sFirst\": \"首页\",\r\n");
      out.write("\t         \"sPrevious\": \"前一页\",\r\n");
      out.write("\t         \"sNext\": \"后一页\",\r\n");
      out.write("\t         \"sLast\": \"尾页\"\r\n");
      out.write("\t       }\r\n");
      out.write("\t     }\r\n");
      out.write("\t   });\r\n");
      out.write("\t function login(){\r\n");
      out.write(" \t\tvar myusername = $(\"#myusername\").val();\r\n");
      out.write(" \t\tvar mypassword = $(\"#mypassword\").val();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t if(myusername == \"\")\r\n");
      out.write(" \t\t\t   {\r\n");
      out.write(" \t\t\t   alert(\"请填写用户名！\");\r\n");
      out.write(" \t\t\t   }\r\n");
      out.write(" \t\t   else if(mypassword == \"\")\r\n");
      out.write(" \t\t\t  {\r\n");
      out.write(" \t\t\t \talert(\"请填写密码！\");\r\n");
      out.write(" \t\t\t  }\r\n");
      out.write(" \t\t   else {\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write(" \t\t\turl:\"login\",   \r\n");
      out.write(" \t\t\ttype:\"post\",\r\n");
      out.write(" \t\t\tdata:{\r\n");
      out.write(" \t    \t\t   Name: myusername,\r\n");
      out.write(" \t    \t\t   Password:mypassword,\r\n");
      out.write(" \t    \t\t},\r\n");
      out.write(" \t    \tasync:false,\r\n");
      out.write(" \t\t\tsuccess:function(data){\r\n");
      out.write(" \t\t\t\tif(data != \"\"){\r\n");
      out.write(" \t\t\t\t\talert(\"登录成功\");\r\n");
      out.write(" \t\t\t\t\twindow.location.href=\"首页.jsp\";\r\n");
      out.write(" \t\t\t\t}else{\r\n");
      out.write(" \t\t\t\t\talert(\"登录失败\");\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t},\r\n");
      out.write(" \t\t\terror:function(XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write(" \t\t\t\talert(\"系统错误\");\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t});  \r\n");
      out.write(" \t   \t\t   \r\n");
      out.write(" \t   \t   }\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t}\r\n");
      out.write(" </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
