/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-01-05 19:41:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 首页_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>CONVEST</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Google fonts - Roboto-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,700\">\r\n");
      out.write("    <!-- Bootstrap Select-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/bootstrap-select/css/bootstrap-select.min.css\">\r\n");
      out.write("    <!-- owl carousel-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/owl.carousel/assets/owl.theme.default.css\">\r\n");
      out.write("    <!-- theme stylesheet-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.default.css\" id=\"theme-stylesheet\">\r\n");
      out.write("    <!-- Custom stylesheet - for your changes-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("    <!-- Favicon and apple touch icons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"img/apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"img/apple-touch-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"img/apple-touch-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"img/apple-touch-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"img/apple-touch-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"img/apple-touch-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"img/apple-touch-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"img/apple-touch-icon-152x152.png\">\r\n");
      out.write("    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"all\">\r\n");
      out.write("      <!-- Top bar-->\r\n");
      out.write("      <div class=\"top-bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex align-items-center\">\r\n");
      out.write("            <div class=\"col-md-6 d-md-block d-none\">\r\n");
      out.write("              <p>联系我们 +86 123456789 或者发送email至convest@gmail.com</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <div class=\"d-flex justify-content-md-end justify-content-between\">\r\n");
      out.write("                <ul class=\"list-inline contact-info d-block d-md-none\">\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-phone\"></i></a></li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a href=\"#\"><i class=\"fa fa-envelope\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"login\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\" class=\"login-btn\"><i class=\"fa fa-sign-in\"></i><span class=\"d-none d-md-inline-block\">登录</span></a><a href=\"customer-register.jsp\" class=\"signup-btn\"><i class=\"fa fa-user\"></i><span class=\"d-none d-md-inline-block\">注册</span></a></div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Top bar end-->\r\n");
      out.write("      <!-- Login Modal-->\r\n");
      out.write("      <div id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"login-modalLabel\" aria-hidden=\"true\" class=\"modal fade\">\r\n");
      out.write("        <div role=\"document\" class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <h4 id=\"login-modalLabel\" class=\"modal-title\">用户登录</h4>\r\n");
      out.write("              <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">×</span></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("               <form action=\"个人中心.jsp\" method=\"get\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"myusername\" type=\"text\" placeholder=\"用户名\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input id=\"mypassword\" type=\"password\" placeholder=\"密码\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"text-center\">\r\n");
      out.write("                  <button class=\"btn btn-template-outlined\" onclick=\"login()\"><i class=\"fa fa-sign-in\"></i> 登录</button>\r\n");
      out.write("                </p>\r\n");
      out.write("              </form>\r\n");
      out.write("              <p class=\"text-center text-muted\">还没注册？</p>\r\n");
      out.write("              <p class=\"text-center text-muted\"><a href=\"customer-register.jsp\"><strong>即刻注册</strong></a>! 只需一分钟，体验更多功能！</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Login modal end-->\r\n");
      out.write("      <!-- Navbar Start-->\r\n");
      out.write("      <header class=\"nav-holder make-sticky\">\r\n");
      out.write("        <div id=\"navbar\" role=\"navigation\" class=\"navbar navbar-expand-lg\">\r\n");
      out.write("          <div class=\"container\"><a href=\"首页.jsp\" class=\"navbar-brand home\"><img src=\"img/logo.png\" alt=\"Universal logo\" class=\"d-none d-md-inline-block\"><img src=\"img/logo-small.png\" alt=\"Universal logo\" class=\"d-inline-block d-md-none\"><span class=\"sr-only\">Universal - go to homepage</span></a>\r\n");
      out.write("            <button type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" class=\"navbar-toggler btn-template-outlined\"><span class=\"sr-only\">Toggle navigation</span><i class=\"fa fa-align-justify\"></i></button>\r\n");
      out.write("            <div id=\"navigation\" class=\"navbar-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item dropdown active\"><a href=\"首页.jsp\" >首 页 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"高管信息.jsp\">高管信息 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"股票信息.jsp\" >股票信息<b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"社区资讯.jsp\" >社区资讯 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item dropdown menu-large\"><a href=\"个人中心.jsp\" >个人中心 <b class=\"caret\"></b></a>\r\n");
      out.write("                  \r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- ========== Contact dropdown end ==================-->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"search\" class=\"collapse clearfix\">\r\n");
      out.write("              <form role=\"search\" class=\"navbar-form\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Search\" class=\"form-control\"><span class=\"input-group-btn\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-template-main\"><i class=\"fa fa-search\"></i></button></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <!-- Navbar End-->\r\n");
      out.write("      \r\n");
      out.write("      <section class=\"no-mb relative-positioned\">\r\n");
      out.write("        <!--\r\n");
      out.write("        *** JUMBOTRON ***\r\n");
      out.write("        _________________________________________________________\r\n");
      out.write("        -->\r\n");
      out.write("        <div style=\"background: url('img/photogrid.jpg') center center repeat; background-size: cover;\" class=\"jumbotron relative-positioned color-white text-md-center\">\r\n");
      out.write("          <div class=\"dark-mask mask-primary\"></div>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row mb-small\">\r\n");
      out.write("              <div class=\"col-md-12 text-center\">\r\n");
      out.write("                <h1 class=\"text-uppercase\">通过数字科技赋能投资升级</h1>\r\n");
      out.write("                <h2 class=\"text-uppercase\">基于另类大数据，CONVEST帮助投资者获取有效的数据、信息、知识，辅助投资者做出正确的决策\r\n");
      out.write("                </h2>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 mb-small\"><img src=\"img/template-mac.png\" alt=\"...\" class=\"img-fluid\"></div>\r\n");
      out.write("              <div class=\"col-md-6 text-center-sm\">\r\n");
      out.write("                <p class=\"no-letter-spacing\">CONVEST是专业的投资市场情报平台，其数据涵盖A股全部上市公司高管信息网络、上市公司财报信息、交易事件库、财经新闻、其他另类数据库等各类详尽信息， 帮助客户快速获取有用的数据和信息，做出正确的决策。</p>\r\n");
      out.write("                <p>\r\n");
      out.write("                   <a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\" class=\"scroll-to btn btn-template-outlined-white\">开启体验</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- *** JUMBOTRON END ***-->\r\n");
      out.write("      </section>\r\n");
      out.write("      <section class=\"bar bg-gray no-mb padding-big text-md-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <h2 class=\"text-uppercase\">资讯跟踪</h2>\r\n");
      out.write("              <p class=\"lead mb-small\">投资资讯实时跟踪</p>\r\n");
      out.write("              <p class=\"mb-small\">满足客户个性化定制需求，为客户提供准确、及时、完整的落地数据，内容涵盖融资、团队、舆情、竞品、情报等公司发展数据，和基金、工商、股票、研报等各类金融市场数据。</p>\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 text-center\"><img src=\"img/template-easy-customize2.png\" alt=\"\" class=\"img-fluid\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section class=\"bar no-mb color-white padding-big text-md-center bg-primary\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 text-center\"><img src=\"img/template-tablets.png\" alt=\"\" class=\"img-fluid\"></div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <h2 class=\"text-uppercase\">高管信息网络</h2>\r\n");
      out.write("              <p class=\"lead mb-small\">上市公司高管信息图谱</p>\r\n");
      out.write("              <p class=\"mb-small\">基于深度学习模型构建的上市公司高管知识图谱，将高管简历信息进行深度挖掘，人际关系、资本动向、财报造假等投资风险一目了然。</p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section class=\"bar bg-gray no-mb padding-big text-center-sm\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <h2 class=\"text-uppercase\">可视化系统</h2>\r\n");
      out.write("              <p class=\"mb-small\">将高管网络数据进行直观清晰的可视化呈现，并基于经典财务模型帮助投资者在最大程度上节省时间，辅助做出最为明智的投资决策。</p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 text-center\"><img src=\"img/template-easy-code.png\" alt=\"\" class=\"img-fluid\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- FOOTER -->\r\n");
      out.write("      <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">联系方式</h4>\r\n");
      out.write("              <p>企业邮箱：<a href=\"mailto:CONVEST@gmail.com\" rel=\"nofollow\">CONVEST@gmail.com</a></p>\r\n");
      out.write("              <p>联系电话：+86 1234567</p>\r\n");
      out.write("              <p>工作时间：周一至周五：9:30-17:00</p>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <h4 class=\"h6\">真诚欢迎合作者的到来！</h4>\r\n");
      out.write("              \r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">数据来源</h4>\r\n");
      out.write("              <p><a href=\"http://zxgk.court.gov.cn/\" target=\"_blank\" rel=\"nofollow\">中国执行信息公开网</a></p>\r\n");
      out.write("              <p><a href=\"http://www.sipo.gov.cn/\" target=\"_blank\" rel=\"nofollow\">国家知识产权局</a></p>\r\n");
      out.write("              <p><a href=\"http://sbj.cnipa.gov.cn/\" target=\"_blank\" rel=\"nofollow\">商标局</a></p>\r\n");
      out.write("              <p><a href=\"http://www.ncac.gov.cn/\" target=\"_blank\" rel=\"nofollow\">版权局</a></p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("              <h4 class=\"h6\">办公地址</h4>\r\n");
      out.write("              <p class=\"text-uppercase\"><strong>中国上海杨浦区</strong><br>国定路777号 <br>上海财经大学<br>信息管理与工程学院<br><strong></strong></p><a href=\"contact.jsp\" class=\"btn btn-template-main\">前往联系界面</a>\r\n");
      out.write("              <hr class=\"d-block d-lg-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyrights\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-lg-4 text-center-md\">\r\n");
      out.write("                <p>&copy; 2020. CONVEST</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Javascript files-->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/popper.js/umd/popper.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.cookie/jquery.cookie.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/waypoints/lib/jquery.waypoints.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/jquery.counterup/jquery.counterup.min.js\"> </script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.parallax-1.1.3.js\"></script>\r\n");
      out.write("    <script src=\"vendor/bootstrap-select/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery.scrollto/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("    <script src=\"js/front.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function login(){\r\n");
      out.write("\t\tvar myusername = $(\"#myusername\").val();\r\n");
      out.write("\t\tvar mypassword = $(\"#mypassword\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t if(myusername == \"\")\r\n");
      out.write("\t\t\t   {\r\n");
      out.write("\t\t\t   alert(\"请填写用户名！\");\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t   else if(mypassword == \"\")\r\n");
      out.write("\t\t\t  {\r\n");
      out.write("\t\t\t \talert(\"请填写密码！\");\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t   else {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"login\",   \r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t    \t\t   Name: myusername,\r\n");
      out.write("\t    \t\t   Password:mypassword,\r\n");
      out.write("\t    \t\t},\r\n");
      out.write("\t    \tasync:false,\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data != \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"登录成功\");\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"首页.jsp\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"登录失败\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\talert(\"系统错误\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});  \r\n");
      out.write("\t   \t\t   \r\n");
      out.write("\t   \t   }\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
