/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-12-24 08:07:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.maps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;

public final class Address_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.mysql.jdbc.Driver");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>VACARE - 知苗</title>\r\n");
      out.write("     <!--\r\n");
      out.write("\r\n");
      out.write("    Template 2106 Soft Landing\r\n");
      out.write("\r\n");
      out.write("\thttp://www.tooplate.com/view/2106-soft-landing\r\n");
      out.write("\r\n");
      out.write("    -->\r\n");
      out.write("     <meta charset=\"UTF-8\">\r\n");
      out.write("     <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("     <meta name=\"description\" content=\"\">\r\n");
      out.write("     <meta name=\"keywords\" content=\"\">\r\n");
      out.write("     <meta name=\"team\" content=\"\">\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/owl.carousel.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <!-- MAIN CSS -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/tooplate-style.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/record.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- PRE LOADER -->\r\n");
      out.write("     <section class=\"preloader\">\r\n");
      out.write("          <div class=\"spinner\">\r\n");
      out.write("\r\n");
      out.write("               <span class=\"spinner-rotate\"></span>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \t<!-- MENU -->\r\n");
      out.write("\t<section class=\"navbar custom-navbar navbar-fixed-top top-nav-collapse\" role=\"navigation\" id=\"start\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t <div class=\"navbar-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  <!-- lOGO TEXT HERE -->\r\n");
      out.write("\t\t\t\t  <a href=\"../index.jsp\" class=\"navbar-brand\">VACARE</a>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t <!-- MENU LINKS -->\r\n");
      out.write("\t\t\t <div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t  <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../index.jsp\" class=\"smoothScroll\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../info/information.jsp\" class=\"smoothScroll\">疫苗资讯</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../info/query.jsp\" class=\"smoothScroll\">疫苗查询</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../maps/direction.jsp\" class=\"smoothScroll\">疫苗流向</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../maps/address.jsp\" class=\"smoothScroll\">接种信息</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"../record/note.jsp\" class=\"smoothScroll\">疫苗本</a></li>\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t  <ul class=\"nav navbar-nav\" style=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t   <!-- 小人菜单栏-->\r\n");
      out.write("\t\t\t\t\t   <li class=\"dropdown\"><a href=\"../user/login.jsp\" title=\"登录注册\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"fa fa-user-circle-o fa-lg\"></i></a>\r\n");
      out.write("\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t   <li class=\"dropdown\"><a data-toggle=\"dropdown\" title=\"修改信息\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"fa fa-cog fa-lg\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu settings-menu dropdown-menu-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=\"../user/Info.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-edit fa-lg\"></i> &nbsp;个人资料</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=\"../user/Password.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-cog fa-lg\"></i> &nbsp;修改密码</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=");
      out.print(request.getContextPath() +"/exit");
      out.write("><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-sign-out fa-lg\"></i>&nbsp; 安全退出</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- FEATURE -->\r\n");
      out.write("     <section id=\"record\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                         <div class=\"block\">\r\n");
      out.write("                              <div class=\"block-body\" style=\"padding-bottom: 0px;\">\r\n");
      out.write("                                   <div class=\"page-header\">\r\n");
      out.write("                                        <h2>接种信息 &nbsp; <small>接种疫苗及地点展示</small></h2>  \r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   \r\n");
      out.write("                              </div>\r\n");
      out.write("                               \r\n");
      out.write("                              \r\n");
      out.write("    <fieldset align=\"center\">\r\n");
      out.write("      \r\n");
      out.write("        <form action=\"#\">\r\n");
      out.write("           \r\n");
      out.write("         \r\n");
      out.write("            <label for=\"addr-show\">您选择的是：\r\n");
      out.write("                <input type=\"text\" value=\"\" id=\"addr-show\">\r\n");
      out.write("            </label>\r\n");
      out.write("            <!--省份选择-->\r\n");
      out.write("            <select id=\"prov\" onchange=\"showCity(this)\">\r\n");
      out.write("                <option>=请选择省份=</option>\r\n");
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <!--城市选择-->\r\n");
      out.write("            <select id=\"city\" onchange=\"showCountry(this)\">\r\n");
      out.write("                <option>=请选择城市=</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <!--县区选择-->\r\n");
      out.write("            <select id=\"country\" onchange=\"selecCountry(this)\">\r\n");
      out.write("                <option>=请选择县区=</option>\r\n");
      out.write("            </select>\r\n");
      out.write("             <select id=\"type\" onchange=\"selecType(this)\">\r\n");
      out.write("                <option>=请选择类型=</option>\r\n");
      out.write("                <option value=\"dog\" >狂犬疫苗</option>\r\n");
      out.write("    \t\t\t<option value=\"station\">普通疫苗</option>\r\n");
      out.write("    \t\t\t<option value=\"hpv\">hpv</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"button\" class=\"btn met1\" >确定</button>\r\n");
      out.write("            </br>\r\n");
      out.write("        </form>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("\r\n");
      out.write("</br>\r\n");
      out.write("                              <div class=\"card\" align=\"center\">\r\n");
      out.write("                              <div id=\"baidu-map\" style=\"width:95%;height:500px;\" ></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("\r\n");
      out.write("                              \r\n");
      out.write("                              \r\n");
      out.write("                        <div class=\"card\" align=\"center\">\r\n");
      out.write("                               <div style=\"width:90%;padding-top:30px;\" >\r\n");
      out.write("                                <table class=\"table table-hover table-bordered\" id=\"sampleTable\">\r\n");
      out.write("                                   <thead>\r\n");
      out.write("                                     <tr>\r\n");
      out.write("                                     \r\n");
      out.write("                                       <th>名称</th>\r\n");
      out.write("                                       <th>地址</th>\r\n");
      out.write("                                       <th>电话</th>\r\n");
      out.write("                                       <th>时间</th>\r\n");
      out.write("                                     </tr>\r\n");
      out.write("                                   </thead>\r\n");
      out.write("\r\n");
      out.write("\t  <tbody id=\"map-body\">\t\t\r\n");
      out.write("\t </tbody>\r\n");
      out.write("\t <script type=\"text/html\" id=\"map-script\">\r\n");
      out.write("{{each data value i}}\r\n");
      out.write("<tr class=\"table-data-line\">\r\n");
      out.write("<td> {{value.name}}</td>\r\n");
      out.write("<td> {{value.loc}}</td>\r\n");
      out.write("<td> {{value.tel}}</td>\r\n");
      out.write("<td> {{value.time}}</td>\r\n");
      out.write("</tr>\r\n");
      out.write("{{/each}}\t \r\n");
      out.write("\t </script>\r\n");
      out.write("\t </table>\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                         </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("      <!-- FOOTER -->\r\n");
      out.write("      <footer id=\"footer\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                    <div class=\"copyright-text col-md-12 col-sm-12\">\r\n");
      out.write("                         <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                              <p>Copyright &copy; 2020 VACARE - for all</p>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                              <ul class=\"social-icon\">\r\n");
      out.write("                                   <li><a data-scroll style=\"padding: 5px;\" href=\"../index.jsp\">返回首页</a></li>\r\n");
      out.write("\r\n");
      out.write("                              </ul>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- SCRIPTS -->\r\n");
      out.write("     <script src=\"../js/jquery.js\"></script>\r\n");
      out.write("     <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("     <script src=\"../js/jquery.stellar.min.js\"></script>\r\n");
      out.write("     <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("     <script src=\"../js/smoothscroll.js\"></script>\r\n");
      out.write("     <script src=\"../js/custom.js\"></script>\r\n");
      out.write("     <script src=\"../js/template.js\"></script>\r\n");
      out.write(" \t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar wageNowTable;//表格全局变量，不要放在ready函数内，否则就不是全局变量\r\n");
      out.write("\t\tjQuery(document).ready(function() {\r\n");
      out.write("            });\r\n");
      out.write("       </script>\r\n");
      out.write(" <script >\r\n");
      out.write(" $('body').on('click', '.met1', function () { \r\n");
      out.write("\t    \r\n");
      out.write("\t    addrShow.value =provice[current.prov].name + '-' + provice[current.prov][\"city\"][current.city].name + '-' + provice[current.prov][\"city\"][current.city].districtAndCounty[current.country];\r\n");
      out.write("\t    jQuery.noConflict();\r\n");
      out.write("\t    jQuery('#sampleTable').dataTable().fnDestroy();\r\n");
      out.write("\t    jQuery.ajax({\r\n");
      out.write("\t  \r\n");
      out.write("\t        url: \"../Querymap\",\r\n");
      out.write("\t        type: \"post\",\r\n");
      out.write("\t        data:{\r\n");
      out.write("\t        \tcountry:provice[current.prov][\"city\"][current.city].districtAndCounty[current.country],\r\n");
      out.write("\t        \ttype:current.type,\r\n");
      out.write("\t        },\r\n");
      out.write("\t        async: false,\r\n");
      out.write("\t        success: function (data) {\r\n");
      out.write("\t            console.log(data);\r\n");
      out.write("\t            jQuery(\"#map-body\").empty();\r\n");
      out.write("\t            jQuery(\"#map-body\").append(template(\"map-script\", { data: data }));\r\n");
      out.write("\t            \r\n");
      out.write("\t        }, error: function (data) {\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t   \r\n");
      out.write("\t  \tjQuery('#sampleTable').dataTable({\r\n");
      out.write("     \"bLengthChange\": true, //开关，是否显示每页显示多少条数据的下拉框\r\n");
      out.write("     'iDisplayLength': 5, //每页初始显示5条记录\r\n");
      out.write("     'bFilter': true,  //是否使用内置的过滤功能（是否去掉搜索框）\r\n");
      out.write("     \"bInfo\": true, //开关，是否显示表格的一些信息(当前显示XX-XX条数据，共XX条)\r\n");
      out.write("     \"bPaginate\": true, //开关，是否显示分页器\r\n");
      out.write("     \"bSort\": true, //是否可排序 \r\n");
      out.write("\r\n");
      out.write("     \"oLanguage\": {  //语言转换\r\n");
      out.write("       \"sInfo\": \"显示第 _START_ 至 _END_ 项结果，共_TOTAL_ 项\",\r\n");
      out.write("       \"sZeroRecords\": \"暂无数据呜呜呜\",\r\n");
      out.write("       \"sLengthMenu\": \"每页显示 _MENU_ 项结果\",\r\n");
      out.write("       \"oPaginate\": {\r\n");
      out.write("         \"sFirst\": \"首页\",\r\n");
      out.write("         \"sPrevious\": \"前一页\",\r\n");
      out.write("         \"sNext\": \"后一页\",\r\n");
      out.write("         \"sLast\": \"尾页\"\r\n");
      out.write("       }\r\n");
      out.write("     }\r\n");
      out.write("   });\r\n");
      out.write("   var dis=document.getElementById(\"country\");\r\n");
      out.write("   var index1 = dis.selectedIndex;\r\n");
      out.write("   var selectedText1 = dis[index1].text;\r\n");
      out.write("    var city=document.getElementById(\"city\");\r\n");
      out.write("   var index2 = city.selectedIndex;\r\n");
      out.write("   var selectedText2 = city[index2].text;\r\n");
      out.write("   var selectedText=selectedText2+selectedText1;\r\n");
      out.write("   var type=document.getElementById(\"type\");\r\n");
      out.write("   var index3 = type.selectedIndex;\r\n");
      out.write("   var selectedText3 = type[index3].text;\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   var map = new BMap.Map(\"baidu-map\", { enableMapClick: false });\r\n");
      out.write("    map.addControl(new BMap.NavigationControl());               // 添加平移缩放控件\r\n");
      out.write("\tmap.addControl(new BMap.ScaleControl());                    // 添加比例尺控件\r\n");
      out.write("\tmap.addControl(new BMap.OverviewMapControl());              //添加缩略地图控件\r\n");
      out.write("\tmap.enableScrollWheelZoom();                            //启用滚轮放大缩小\r\n");
      out.write("\tmap.centerAndZoom(selectedText, 11);\r\n");
      out.write("\r\n");
      out.write(" var center1,center2;\r\n");
      out.write(" var mylocal = new BMap.LocalSearch(map);\r\n");
      out.write(" mylocal.search(selectedText);\r\n");
      out.write("    mylocal.setSearchCompleteCallback(function (searchResult) {\r\n");
      out.write("        var poi = searchResult.getPoi(0);\r\n");
      out.write("\t\t        center1=poi.point.lng;\r\n");
      out.write("\t\t        center2=poi.point.lat;\r\n");
      out.write("\t\t        map.centerAndZoom(new BMap.Point(center1,center2), 11);\r\n");
      out.write("\t\t    \tmap.enableScrollWheelZoom();                            //启用滚轮放大缩小\r\n");
      out.write("\r\n");
      out.write("\t\t    \tvar local = new BMap.LocalSearch(map, {\r\n");
      out.write("\t\t    \t\trenderOptions:{map: map}\r\n");
      out.write("\t\t    \t});\r\n");
      out.write("\t\t    \tvar pStart = new BMap.Point(center1-0.05,center2-0.02);\r\n");
      out.write("\t\t    \tvar pEnd = new BMap.Point(center1+0.05,center2+0.02);\r\n");
      out.write("\t\t    \tvar bs = new BMap.Bounds(pStart,pEnd);   //自己规定范围\r\n");
      out.write("\t\t    \tif(selectedText3==\"普通疫苗\")\r\n");
      out.write("\t\t    \t{\r\n");
      out.write("\t\t    \t\tlocal.searchInBounds(\"预防接种\", bs);\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \telse{\r\n");
      out.write("\t\t    \t\tlocal.searchInBounds(\"狂犬\", bs);\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\r\n");
      out.write("\t\t    \tvar polygon = new BMap.Polygon([\r\n");
      out.write("\t\t    \t\tnew BMap.Point(pStart.lng,pStart.lat),\r\n");
      out.write("\t\t    \t\tnew BMap.Point(pEnd.lng,pStart.lat),\r\n");
      out.write("\t\t    \t\tnew BMap.Point(pEnd.lng,pEnd.lat),\r\n");
      out.write("\t\t    \t\tnew BMap.Point(pStart.lng,pEnd.lat)\r\n");
      out.write("\t\t    \t\t], {strokeColor:\"blue\", strokeWeight:6, strokeOpacity:0.5});\r\n");
      out.write("\t\t    \tmap.addOverlay(polygon);\r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write(" // 百度地图API功能\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("     <script src=\"http://api.map.baidu.com/api?v=3.0&ak=mNBkTUgdgVT1CHLqeXPOZIHTf8Y7tXIY\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("\r\n");
      out.write("          //map\r\n");
      out.write("          var map = new BMap.Map(\"baidu-map\", { enableMapClick: false });\r\n");
      out.write("         var point = new BMap.Point(120.170507,30.276462);  //以指定的经度和纬度创建一个地理点坐标,(创建坐标点)\r\n");
      out.write("\t\t map.centerAndZoom(point, 11);     // 初始化地图,设置中心点坐标和地图级别\r\n");
      out.write("\t\t \r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     </script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"../js/map.js\"></script>\r\n");
      out.write("<script src=\"../js/method.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
