/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-01-02 08:03:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import dao.directionDao;
import bean.direction;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.directionDao");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("bean.direction");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" +request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<title>VACARE - 知苗</title>\r\n");
      out.write("\t<!--\r\n");
      out.write("\r\n");
      out.write("    Template 2106 Soft Landing\r\n");
      out.write("\r\n");
      out.write("\thttp://www.tooplate.com/view/2106-soft-landing\r\n");
      out.write("\r\n");
      out.write("    -->\r\n");
      out.write("     <meta charset=\"UTF-8\">\r\n");
      out.write("     <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("     <meta name=\"description\" content=\"\">\r\n");
      out.write("     <meta name=\"keywords\" content=\"\">\r\n");
      out.write("     <meta name=\"team\" content=\"\">\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <!-- MAIN CSS -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/tooplate-style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("     <!-- PRE LOADER -->\r\n");
      out.write("     <section class=\"preloader\">\r\n");
      out.write("          <div class=\"spinner\">\r\n");
      out.write("\r\n");
      out.write("               <span class=\"spinner-rotate\"></span>\r\n");
      out.write("               \r\n");
      out.write("          </div>\r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \t<!-- MENU -->\r\n");
      out.write("\t<section class=\"navbar custom-navbar navbar-fixed-top top-nav-collapse\" role=\"navigation\" id=\"start\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t <div class=\"navbar-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  <!-- lOGO TEXT HERE -->\r\n");
      out.write("\t\t\t\t  <a href=\"index.jsp\" class=\"navbar-brand\">VACARE</a>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t <!-- MENU LINKS -->\r\n");
      out.write("\t\t\t <div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t  <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"index.jsp\" class=\"smoothScroll\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"info/information.jsp\" class=\"smoothScroll\">疫苗资讯</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"info/query.jsp\" class=\"smoothScroll\">疫苗查询</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"maps/direction.jsp\" class=\"smoothScroll\">疫苗流向</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"maps/address.jsp\" class=\"smoothScroll\">接种信息</a></li>\r\n");
      out.write("\t\t\t\t\t   <li><a href=\"record/note.jsp\" class=\"smoothScroll\">疫苗本</a></li>\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t  <ul class=\"nav navbar-nav\" style=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t   <!-- 小人菜单栏-->\r\n");
      out.write("\t\t\t\t\t   <li class=\"dropdown\"><a href=\"user/login.jsp\" title=\"登录注册\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"fa fa-user-circle-o fa-lg\"></i></a>\r\n");
      out.write("\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t   <li class=\"dropdown\"><a data-toggle=\"dropdown\" title=\"修改信息\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"fa fa-cog fa-lg\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu settings-menu dropdown-menu-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=\"user/Info.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-edit fa-lg\"></i> &nbsp;个人资料</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=\"user/Password.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-cog fa-lg\"></i> &nbsp;修改密码</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li><a class=\"dropdown-item\" href=");
      out.print(request.getContextPath() +"/exit");
      out.write("><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-sign-out fa-lg\"></i>&nbsp; 安全退出</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- FEATURE -->\r\n");
      out.write("     <section id=\"home\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("          <div class=\"overlay\"></div>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-offset-3 col-md-6 col-sm-12\">\r\n");
      out.write("                         <div class=\"home-info\">\r\n");
      out.write("                              <h3>欢迎使用知苗</h3>\r\n");
      out.write("                              <h1>搜索疫苗相关信息</h1>\r\n");
      out.write("                              <form action=\"QueryVaccine\" method=\"get\" class=\"online-form\">\r\n");
      out.write("                                   <input type=\"text\" style=\"width:60%\" name=\"vaccine\" class=\"form-control\" placeholder=\"输入相关疫苗名称\">\r\n");
      out.write("                                   <button type=\"submit\" class=\"form-control\">搜索</button>\r\n");
      out.write("                              </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("          </div>\r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("     <!-- SCRIPTS -->\r\n");
      out.write("     <script src=\"js/jquery.js\"></script>\r\n");
      out.write("     <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("     <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("     <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("     <script src=\"js/smoothscroll.js\"></script>\r\n");
      out.write("     <script src=\"js/custom.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
